# Streamlit Configuration File
# This config file takes precedence over environment variables
# Prevents Railway from auto-injecting STREAMLIT_SERVER_PORT

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
# Port will be dynamically overridden by start_streamlit.py
port = 8501
address = "0.0.0.0"
baseUrlPath = ""

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[global]
developmentMode = false

[logger]
level = "info"